# Use the official Nginx image as the base image
FROM nginx:alpine

WORKDIR /usr/share/nginx/html/
# Copy the static files into the Nginx HTML directory
# COPY index.html /usr/share/nginx/html/index.html
# COPY styles.css /usr/share/nginx/html/styles.css
# COPY script.js /usr/share/nginx/html/script.js
COPY . .

# Expose port 80
EXPOSE 80

# Command to run Nginx
CMD ["nginx", "-g", "daemon off;"]
