name: Build and Push Docker Image

on:
  push:
    branches:
      - new-style

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the Docker image frontend
      run: |
        docker build -f dockerfile.frontend -t errbx/hifecafe:new-style .
  
    - name: Build the Docker image backend
      run: |
        docker build -f dockerfile.backend -t errbx/hifecafe:backend .
  
    - name: Push the Docker image
      run: |
        docker push errbx/hifecafe:new-style

    - name: Push the Docker image
      run: |
        docker push errbx/hifecafe:backend
